print("Melting and Boiling Points of Alkanes")
print("Name         Melting Point(deg C)        Boiling Point(deg C)")
print("Methane      -162                        -183")
print("Ethane       -89                         -172")
print("Propane      -42                         -188")
print("Butane       -0.5                        -135")